### PR TITLE
Add planned complete date field to product

### PR DESCRIPTION
**Pull request by zkhin**
Fixes https://github.com/SeedCompany/cord-api-v3/issues/2291

### CODE REVIEW

**Comment by zkhin** [comment]
@CarsonF Do we need to put the new field (`plannedCompleteDate `) in the CREATE/UPDATE DTO as well?

**Comment by CarsonF** [comment]
> @CarsonF Do we need to put the new field (`plannedCompleteDate `) in the CREATE/UPDATE DTO as well?

Yes please.

**Comment by CarsonF** [comment]
@zkhin can we also validate that the date is within the engagement date range?

**Comment by zkhin** [comment]
> @zkhin can we also validate that the date is within the engagement date range?

Sure!

**Comment by CarsonF** [comment]
Oh no. I've made a big mistake. I was looking at the PnP file to give you the column to extract from and realized that the date is _per step_ not product 🤦‍♂️ . This brings up larger schema changes, because it basically converts steps from a string to an object. I totally forgot this by the time I was making the ticket. I thought to myself "this is easy, why didn't I make this ticket sooner" OOF.

Still thinking more on best way forward...

**Comment by CarsonF** [comment]
Closing because we are switching directions in #2291. Sorry for the lost work @zkhin.

**Pull request closed without merging**
