### PR TITLE
[EdgeDB] Add Pins Seeding

### PR DESCRIPTION
**Pull request by bryanjnelson**
## Description

Add seeding for pinnable types; some test users now have populated `pins` for projects, languages, and/or partners

- [X] Change the task url above to the actual Monday task
- [N/A] Add/update tests if needed
- [X] Add reviewers to this PR

### CODE REVIEW

**Comment by CarsonF** [comment]
Yeah I'd have pins in its own file.

Update could simply be:
```edgeql
update User
filter .realFirstName = "Bilbo"
set {
  pins += (
    select Mixin::Pinnable
    filter [is Mixin::Named].name = {"Sindarin", "Quenya", "South Downs"}
  )
};
```

**Comment by bryanjnelson** [comment]
Do you think there is enough benefit in keeping the json separated like this into languages, partners, and projects even though they could technically just be one big list of pinnables?

```edgeql
with
  usersJson := to_json('[
    {
      "user": "Bilbo",
      "pinnables": {
        "languages": ["Sindarin", "Quenya"],
        "partners": ["Dwarvish/Elvish Alliance", "Fellowship of Halfing Languages"],
        "projects": ["Emyn Muil", "Arnor Lake", "South Downs"]
      },
    }
  ]'),
```

Basically does seeing that structure at the top introduce enough benefit to see what type of pins we are adding, over flattening that structure into a list of names and having less code overall?

**Comment by CarsonF** [comment]
I don't see much benefit...I would just flatten

**Comment by bryanjnelson** [comment]
@CarsonF - This seems to work correctly, but the printed output is odd to me:

```json
[
  {
    "Modified Users": [
      "Bilbo Baggins",
      "Bilbo Baggins",
      "Bilbo Baggins",
      "Peregrin Took",
      "Peregrin Took",
      "Peregrin Took",
      "Aragorn Son of Arathorn",
      "Aragorn Son of Arathorn",
      "Aragorn Son of Arathorn"
    ]
  }
]
```

I would expect this:

```json
[
  {
    "Modified Users": [
      "Bilbo Baggins",
      "Peregrin Took",
      "Aragorn Son of Arathorn"
    ]
  }
]
```

Probably something simple?

**Comment by CarsonF** [comment]
> Probably something simple?

Need a `distinct` somewhere.
Either
```edgeql
users := distinct (...)
```
or 
```edgeql
modified := distinct (...)
```
or 
```edgeql
modified := (select distinct users ...)
```
all work.

**Review by CarsonF — APPROVED** [review]

**Pull request merged**
