### PR TITLE
Hydrate latest file version with first file id

### PR DESCRIPTION
**Pull request by tmpacifitech**
Fixes https://github.com/SeedCompany/cord-field/issues/786

### CODE REVIEW

**Review by CarsonF — CHANGES_REQUESTED** [review]
This isn't a meaningful change. I believe the issue mentioned is actually just a problem with stale cache in the UI.

**Comment by tmpacifitech** [comment]
> This isn't a meaningful change. I believe the issue mentioned is actually just a problem with stale cache in the UI.

@CarsonF The issue wasn't cache. `createFileVersion` mutation and `children` file resolver returned the first version's name, size, metatype, etc. So I had to fix `hydrate` query to return first version's id with latest version's props (name, size, metatype, ...)

**Comment by CarsonF** [comment]
Well this was an issue before the hydrate refactor #2118, so that tells me the problem isn't here - at least not the same problem.

`props` in the query _should_ only contain `id`, `createdAt`, & `name`. `size` & `metadata` are only stored on the versions.

**Comment by CarsonF** [comment]
Closing this as we've uncovered what the real ask is in https://github.com/SeedCompany/cord-field/issues/786. @tmpacifitech I think it would be best to start fresh with that.

**Pull request closed without merging**
