### PR TITLE
Add defaultFieldRegion to Location

### LINKED ISSUE #1593: Location.defaultFieldRegion
Add `defaultFieldRegion` property to `Location` which is a relation to a `FieldRegion`. It should probably be nullable.

@kjones140's requesting this for DOMO. And since the v2 schema has this relation, so it would be good to maintain this data (albeit in a different capacity).

### PR DESCRIPTION
**Pull request by elisabeth-sorrell**
closes #1593

### CODE REVIEW

**Comment by elisabeth-sorrell** [comment]
tested with update/create/read operations

**Review by CarsonF — APPROVED** [review]
Looks good to me! @michaelmarshall could double check the db queries.

**Comment by CarsonF** [comment]
What about permissions? Do the role files matter right now @michaelmarshall?

What about tests? Should we add some to ensure this relationship is working?

**Comment by elisabeth-sorrell** [comment]
@CarsonF I'll go ahead and add tests FYI @michaelmarshall

**Comment by elisabeth-sorrell** [comment]
@CarsonF just added a test for updating defaultFieldRegion. I went as in depth as the fundingAccount test

**Comment by michaelmarshall** [comment]
@elisabeth-sorrell reminder to flag property additions as schema changes.

**Review by michaelmarshall — APPROVED** [review]

**Pull request merged**
