### PR TITLE
[EdgeDB] Create `Funding Account` queries

### PR DESCRIPTION
**Pull request by bryanjnelson**
[Monday Task](https://seed-company-squad.monday.com/boards/3451697530/pulses/5587667061)

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/5589534725) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by CarsonF — CHANGES_REQUESTED** [review]
After #2986 is merged, this should be able to become
```ts
@Injectable()
export class FundingAccountEdgedbRepository
  extends RepoFor(FundingAccount).withDefaults() {}
```

**Comment by bryanjnelson** [comment]
> After #2986 is merged, this should be able to become
> 
> ```ts
> @Injectable()
> export class FundingAccountEdgedbRepository
>   extends RepoFor(FundingAccount).withDefaults()
>   implements PublicOf<FundingAccountRepository>
> {}
> ```

I've updated this locally, but am receiving this error on the class:

```
Class 'FundingAccountEdgedbRepository' incorrectly implements interface 'PublicOf<FundingAccountRepository>'.
  The types returned by 'update(...)' are incompatible between these types.
    Type 'Promise<{ id: ID; name: string; createdAt: DateTime; modifiedAt: DateTime; accountNumber: number; }>' is not assignable to type 'Promise<FundingAccount>'.
      Type '{ id: ID; name: string; createdAt: DateTime; modifiedAt: DateTime; accountNumber: number; }' is not assignable to type 'FundingAccount'.
        Property 'canDelete' is missing in type '{ id: ID; name: string; createdAt: DateTime; modifiedAt: DateTime; accountNumber: number; }' but required in type 'FundingAccount'.ts(2420)
resource.dto.ts(54, 12): 'canDelete' is declared here.
```

Was this expected?

**Comment by CarsonF** [comment]
I'm sure we'll need to adjust existing repos as we go to fit new direction. Some blocks are years old anyways.

Change https://github.com/SeedCompany/cord-api-v3/blob/8ae7d53c17d9c2daf3c414067c65a28059b2eee2/src/components/funding-account/funding-account.repository.ts#L38 to 
```ts
    existing: UnsecuredDto<FundingAccount>,
```
And the service method to
```ts
  async update(
    input: UpdateFundingAccount,
    session: Session,
  ): Promise<FundingAccount> {
    const fundingAccount = await this.repo.readOne(input.id);

    const changes = this.repo.getActualChanges(fundingAccount, input);
    this.privileges
      .for(session, FundingAccount, fundingAccount)
      .verifyChanges(changes);
    const updated = await this.repo.update(fundingAccount, changes);
    return await this.secure(updated, session);
  }
```

**Comment by CarsonF** [comment]
Need to register in module as well

**Review by CarsonF — APPROVED** [review]
BIG :shipit:

**Comment by bryanjnelson** [comment]
`splitDB` - nice!

**Pull request merged**
