### PR TITLE
Return file content instead of stream

### LINKED ISSUE #2120: createPartnership > Uploaded  "mou" and "agreement" files are not displayed properly after downloading
**Roles:** Administrator

**Describe the bug**
createPartnership > Uploaded  `mou` and `agreement` files are not displayed properly after downloading

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
File should be displayed properly

**Actual Result**
Uploaded  `mou` and `agreement` files are not displayed properly after downloading.

See video -  

https://user-images.githubusercontent.com/5212585/132319050-a5b2b94a-e503-4e6f-8acf-b7f683f4fb2a.mp4

**GraphQL Query:(createPartnership)**
image

**GraphQL response**
```
{
    "data": {
        "createPartnership": {
            "partnership": {
                "id": "x17NUahuA1L",
                "createdAt": "2021-09-07T09:14:18.915Z",
                "canDelete": true,
                "types": {
                    "value": [
                        "Managing"
                    ],
                    "canRead": true,
                    "canEdit": true
                },
                "agreementStatus": {
                    "value": "Signed",
                    "canRead": true,
                    "canEdit": true
                },
                "mouStatus": {
                    "value": "NotAttached",
                    "canRead": true,
                    "canEdit": true
                },
                "mouStart": {
                    "value": "2021-09-07",
                    "canRead": true,
                    "canEdit": false
                },
                "mouEnd": {
                    "value": "2021-09-07",
                    "canRead": true,
                    "canEdit": false
                },
                "mouStartOverride": {
                    "value": "2021-09-07",
                    "canRead": true,
                    "canEdit": true
                },
                "mouEndOverride": {
                    "value": "2021-09-07",
                    "canRead": true,
                    "canEdit": true
                },
                "mou": {
                    "canRead": true,
                    "canEdit": true,
                    "value": {
                        "id": "Twipl3YbBiY",
                        "createdAt": "2021-09-07T09:14:18.936Z",
                        "type": "File",
                        "mimeType": "image/png",
                        "name": "MOU",
                        "size": 503111,
                        "modifiedAt": "2021-09-07T09:14:18.995Z",
                        "downloadUrl": "http://localhost:3000/file?signed=%7B%22operation%22%3A%22getObject%22%2C%22key%22%3A%22yh2jk8L22RE%22%2C%22expires%22%3A1631006959666%7D",
```

**Query and Input File**
[FileDownloadBug.txt](https://github.com/SeedCompany/cord-api-v3/files/7120431/FileDownloadBug.txt)

CordAPIV3# 396c033

### PR DESCRIPTION
**Pull request by tmpacifitech**
Fixes #2120

### CODE REVIEW

**Review by CarsonF — CHANGES_REQUESTED** [review]
This needs to be a `Readable` as defined by the abstract class 
https://github.com/SeedCompany/cord-api-v3/blob/b39e918b944b12e33516a2dce11da045ac199cbf/src/components/file/bucket/file-bucket.ts#L37-L37
https://github.com/SeedCompany/cord-api-v3/blob/b39e918b944b12e33516a2dce11da045ac199cbf/src/components/file/bucket/file-bucket.ts#L13-L14

I thought TS would enforce this, but I guess it allows subclasses to change return types.

**Comment by tmpacifitech** [comment]
@CarsonF Do you mean that I have to change it to `Buffer` instead of `Readable` or you want to keep it as `Readable`?
```
 type GetObjectOutput = Merge<AwsGetObjectOutput, { Body: Buffer }>; 
```

**Comment by CarsonF** [comment]
I think keeping it as `Readable` is cleaner as that's the way aws gives it to us. But if we need to change it to `Buffer` I'll allow it.

I think the problem might actually be here https://github.com/SeedCompany/cord-api-v3/blob/b39e918b944b12e33516a2dce11da045ac199cbf/src/components/file/local-bucket.controller.ts#L58
Since this changed to a stream instead of a buffer this doesn't work anymore.
I think this will work:
```ts
out.Body.pipe(res);
```

**Comment by tmpacifitech** [comment]
@CarsonF I tried with stream pipe and it worked.

**Comment by CarsonF** [comment]
You can upload & download a file and it view correctly from UI?

**Comment by tmpacifitech** [comment]
> You can upload & download a file and it view correctly from UI?

Yup, I tested it and it worked!

**Review by CarsonF — APPROVED** [review]

**Pull request merged**
