### PR TITLE
Add v2 engagement statuses

### PR DESCRIPTION
**Pull request by blakekrammes**

### CODE REVIEW

**Comment by CarsonF** [comment]
Can you note the v2 ones that will only be used with legacy projects?

**Comment by blakekrammes** [comment]
> Can you note the v2 ones that will only be used with legacy projects?

Are all the added ones v2 only?

**Comment by CarsonF** [comment]
@sethmcknight ^

**Comment by blakekrammes** [comment]
@sethmcknight are the following only from v2?

Converted = 'Converted',
Unapproved = 'Unapproved',
Transferred = 'Transferred',
NotRenewed = 'NotRenewed',
Rejected = 'Rejected',

**Review by michaelmarshall — APPROVED** [review]

**Pull request merged**
