### PR TITLE
Update role permissions for mou and financialReportingType

### PR DESCRIPTION
**Pull request by tmpacifitech**
Fixes https://github.com/SeedCompany/cord-api-v3/issues/2134

### CODE REVIEW

**Comment by CarsonF** [comment]
@sethmcknight I'd like to verify this with you

**Review by CarsonF — CHANGES_REQUESTED** [review]
Looks good @tmpacifitech. I verified with Seth, and he made a couple tweaks to the ask. It looks like there are a couple more roles we need to account for with this change.
Can you take a look?

**Comment by tmpacifitech** [comment]
@CarsonF can you take a look again?

**Review by CarsonF — APPROVED** [review]
Thanks @tmpacifitech!

**Pull request merged**
