### PR TITLE
Tweak partner update/create dto in order to make address clearable

### LINKED ISSUE #1747: Partner.address cannot be cleared
## Environment

| Tech      | Version / Name |
| --------- | -------------- |
| API       |                |
| FE        |                |
| OS/Device |                |
| Browser   |                |

### PR DESCRIPTION
**Pull request by daniel-leod**
Fixes #1747

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466529600) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by CarsonF — CHANGES_REQUESTED** [review]
I think previously we still accepted `null` which should clear it. The UI never sent a null value though. I'd prefer that rather than an empty string. I don't like using empty strings as the lack of a value, that's what null is for.

**Comment by CarsonF** [comment]
You tried via the UI or GQL directly?

**Comment by daniel-leod** [comment]
@CarsonF I tried via GQL directly

**Comment by CarsonF** [comment]
Hmm I'd start with that then, the API should accept and save null. Also the types should be updated.
```diff
-  readonly address: SecuredString;
+  readonly address: SecuredStringNullable;
```
```diff
-  readonly address?: string;
+  readonly address?: string | null;
```

**Review by CarsonF — COMMENTED** [review]
This breaking change is true, because the UI references the [field type explicitly with a fragment](https://github.com/SeedCompany/cord-field/blob/42af25d6fbd7b46c2dcf408937c509156c18463e/src/scenes/Partners/Detail/PartnerDetail.graphql#L47-L49).
Can solve by doing [this](https://github.com/SeedCompany/cord-field/blob/42af25d6fbd7b46c2dcf408937c509156c18463e/src/common/fragments/user.graphql#L4-L10).

**Comment by CarsonF** [comment]
If
```gql
mutation {
  updatePartner(input: { partner: {
    id: "asdf"
    address: null
 }}) {
  partner {
    address { value }
  }
}
```
doesn't work then this we should fix whatever's happening in the service/repository file. Does this work?

**Review by CarsonF — APPROVED** [review]
I'm good with this GQL schema breaking change. As long as the UI is updated & deployed first to mitigate referencing this type directly. https://github.com/SeedCompany/cord-field/pull/1133

**Comment by sethmcknight** [comment]
This lived to the end of its lifetime and died

**Pull request closed without merging**
