### PR TITLE
Throw error when uploadIds are empty #1598

### PR DESCRIPTION
**Pull request by elisabeth-sorrell**

### CODE REVIEW

**Comment by CarsonF** [comment]
This is should be validated automatically but they aren't because of some missing decorators. I'll fix in another PR.

How does this correspond to #1598?

**Comment by elisabeth-sorrell** [comment]
> This is should be validated automatically but they aren't because of some missing decorators. I'll fix in #1628
> 
> How does this correspond to #1598?

A little complicated, but #1597 and #1598 both correspond with the following steps:
- createPartnership with an empty value for uploadId on agreement or mou
- try to create partnership again (since there was an createFileVersion error last time)
- error from having a duplicate partnership

the problem came in when the partnership is created before the uploadId verification, so that there is a partnership created, but it throws an error. Since there's no rollback after the error, there's a duplicate partnership error when the createPartnership is attempted again.

**Comment by elisabeth-sorrell** [comment]
@CarsonF oh, and would you not mind linking #1598 and #1597 to #1628?

**Comment by CarsonF** [comment]
Ok so the invalid input resulted in a partially mutated db state.
Two solutions:
1. Validated complete input before starting anything, which #1628 does.
2. Apply transactions so that errors during mutations rollback the db state instead of leaving it partially applied. I have a branch for this as well. Will PR soon.

**Comment by elisabeth-sorrell** [comment]
Closing since it's handled by #1628

**Pull request closed without merging**
