### PR TITLE
add test case in budget

### PR DESCRIPTION
**Pull request by izquierdoalfredo**
https://github.com/SeedCompany/cord-api-v3/issues/1040

### CODE REVIEW

**Comment by izquierdoalfredo** [comment]
Yes, I relpaced toThrow method by expectNotFound

**Comment by CarsonF** [comment]
This coded before the validation pipe was re-enabled on e2e tests. It should be rebased and error messaged updated to actually assert what the test says it's asserting.

**Review by CarsonF — COMMENTED** [review]
Other than list of budgets we decided on slack that these tests aren't necessary. They are the same src code used across the entire codebase and don't need to be tested in every module

**Comment by elisabeth-sorrell** [comment]
@CarsonF or @michaelmarshall Can you take another look and see if ready for merge? thanks

**Review by CarsonF — APPROVED** [review]

**Pull request merged**
