### PR TITLE
Test creating literacy material

### PR DESCRIPTION
**Pull request by izquierdoalfredo**
https://github.com/SeedCompany/cord-api-v3/issues/1091

There is no bug in code. You used wrong type of scriptureReferences. It is needed to use array of scriptureReferences.

It's a  correct input for postman query
[createLiteracyMaterial_ERR_dueto_ScriptRef - Work.txt](https://github.com/SeedCompany/cord-api-v3/files/5164608/createLiteracyMaterial_ERR_dueto_ScriptRef.-.Work.txt)

Also You used wrong value for book name, book list present in src/components/scripture/books.ts:20. You need to use name from array, but only word, not whole name

for example,
image
only "Exodus" or "Ex" or "Exo" can be used
image

### CODE REVIEW

**Comment by CarsonF** [comment]
@izquierdoalfredo can you post your description as a reply to that issue?

**Comment by izquierdoalfredo** [comment]
Yes, I posted my comments in that issue

**Comment by tjgersho** [comment]
This PR might be the partial duplicate of https://github.com/SeedCompany/cord-api-v3/pull/1084 while causing a conflict.

**Comment by izquierdoalfredo** [comment]
I will check after merge #1084

**Comment by izquierdoalfredo** [comment]
I fixed merge conflict.

**Review by reneepe — COMMENTED** [review]
Reviewed with question in https://github.com/SeedCompany/cord-api-v3/issues/1091

**Review by reneepe — COMMENTED** [review]
VERIFIED - 'Could not create literacy material' error only occurred when 'scriptureReferences' field had invalid data in the query input.

When valid data is entered for the 'scriptureReferences' field in query input, correct results are returned.

Results in https://github.com/SeedCompany/cord-api-v3/issues/1091.

**Comment by CarsonF** [comment]
What's the status of this? Currently it's showing no changes. Can it be closed?

**Comment by izquierdoalfredo** [comment]
@CarsonF 
Piyush told me this ticket can closed

**Pull request closed without merging**
