### PR TITLE
Jest 26 → 29

### PR DESCRIPTION
**Pull request by atGit2021**
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3645568369) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by bryanjnelson — APPROVED** [review]
Looks good to me!

**Comment by atGit2021** [comment]
@bryanjnelson @CarsonF , I was researching the dedupe issue in the Lint/lint test.  I came across this recommendation in my research, see below.  I wanted to get your thoughts on proper steps to resolve before attempting anything.  

_If you want the smallest number of packages in your yarn.lock file, you'll want to execute the utility npm module yarn-deduplicate immediately after adding or upgrading yarn packages, ie:
**npm install -g yarn-deduplicate
yarn-deduplicate yarn.lock**
This utility will analyze and optimize the yarn.lock file so that all version dependencies are satisfied with a minimal set of modules._

**Comment by CarsonF** [comment]
Just need to run
```
yarn dedupe
```

**Comment by atGit2021** [comment]
> Just need to run
> 
> ```
> yarn dedupe
> ```

in my local, recommit, and push again?

**Comment by CarsonF** [comment]
Correct!

**Comment by bryanjnelson** [comment]
The e2e is breaking due to us being a victim of [this breaking change](https://github.com/facebook/jest/blob/main/CHANGELOG.md#2700) upon the upgrade to v27:

image

**Pull request merged**
