### PR TITLE
Fix delete partnership bug related budget records

### PR DESCRIPTION
**Pull request by zkhin**
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1259

### CODE REVIEW

**Review by CarsonF — COMMENTED** [review]
This should not care what event listeners are attached to this event.
Is it not possible to update the logic in the sync budget records listener?

If not (which I would be hard pressed to believe), or if it's too hard (more likely) we can make this change, but outside of the try/catch and without the comment and we should probably rename it to something like `PartnershipWillDelete`.

**Comment by zkhin** [comment]
> This should not care what event listeners are attached to this event.
> Is it not possible to update the logic in the sync budget records listener?
> 
> If not (which I would be hard pressed to believe), or if it's too hard (more likely) we can make this change, but outside of the try/catch and without the comment and we should probably rename it to something like `PartnershipWillDelete`.

This part(https://github.com/SeedCompany/cord-api-v3/blob/master/src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts#L44~L55) is the source of this bug. Because partnership is already deleted and it cannot get any budget records related to that partnership. So I think we should deactivate the budget records before the partnership is deleted. So can I change the event name to `PartnershipWillDeleteEvent`?

**Comment by CarsonF** [comment]
Ok that does sound like the easest solution. So we are just "un-hacking" it a bit :wink:

**Review by CarsonF — APPROVED** [review]
Thanks @zkhin!

**Pull request merged**
