### PR TITLE
Add nullable pointOfContact to Partner module

### PR DESCRIPTION
**Pull request by zkhin**
Fixes: https://github.com/SeedCompany/cord-api-v3/issues/1164

### CODE REVIEW

**Comment by CarsonF** [comment]
Hey @zkhin sorry I missed this ticket after we talked. This actually should go on the Partner object. I thought you were working on that first thing?

**Comment by zkhin** [comment]
Yes trying to focus on partners module now. I was working on a few other tickets and waiting if a partners module ticket. Could we create a ticket based on "Org -> Partner -> Partnership -> Project"?

**Comment by CarsonF** [comment]
> Could we create a ticket based on "Org -> Partner -> Partnership -> Project"?

Sure here -> #1196

**Review by CarsonF — CHANGES_REQUESTED** [review]
Noting for my records

**Review by CarsonF — APPROVED** [review]
Thanks @zkhin!

**Pull request merged**
