### PR TITLE
Limit concurrency for report sync

### PR DESCRIPTION
**Pull request by blakekrammes**

### CODE REVIEW

**Comment by blakekrammes** [comment]
@tmpacifitech if you want to make changes and own this, feel free too. This is just what I wrote up to test out more limited concurrency and it looks like it's working.

**Review by tmpacifitech — APPROVED** [review]
This looks good. Thank you @blakekrammes !

**Comment by blakekrammes** [comment]
I believe the logic is correct now, but we should do another check once we're ready to migrate.

**Comment by blakekrammes** [comment]
Closing in favor of one migration branch that has this code and the code for moving existing P&P files to periodic reports.

**Pull request closed without merging**
