### PR TITLE
Revised PnP error message

### PR DESCRIPTION
**Pull request by atGit2021**
[Monday ](https://seed-company-squad.monday.com/boards/5989610236/pulses/7994409983)

### CODE REVIEW

**Review by CarsonF — COMMENTED** [review]
I'd really rather not store this link in the db for every error.
Can we just a generic link to the UI instead?

**Comment by atGit2021** [comment]
> I'd really rather not store this link in the db for every error. Can we just a generic link to the UI instead?

when you say "generic link", do you mean just use this [link](https://github.com/SeedCompany/cord-docs/wiki/PnP-Extraction-Validation:-Errors-and-Troubleshooting-Steps) which just points to the overall page vs using the specific links that point to the relative error within the page?  And if so, do you want me to pull it from the local.eve config file?

**Comment by CarsonF** [comment]
> when you say "generic link", do you mean just use this [link](https://github.com/SeedCompany/cord-docs/wiki/PnP-Extraction-Validation:-Errors-and-Troubleshooting-Steps) which just points to the overall page vs using the specific links that point to the relative error within the page? And if so, do you want me to pull it from the local.env config file?

Yeah and no it could be hard coded. If that's not acceptable I think we need to do something else.

**Comment by atGit2021** [comment]
> > when you say "generic link", do you mean just use this [link](https://github.com/SeedCompany/cord-docs/wiki/PnP-Extraction-Validation:-Errors-and-Troubleshooting-Steps) which just points to the overall page vs using the specific links that point to the relative error within the page? And if so, do you want me to pull it from the local.env config file?
> 
> Yeah and no it could be hard coded. If that's not acceptable I think we need to do something else.

I think it will be ok, but will ping product team to confirm

**Comment by CarsonF** [comment]
Pulled into #3342

**Pull request closed without merging**
