### PR TITLE
add pull request template

### PR DESCRIPTION
**Pull request by andrewmurraydavid**
## Reason for this PR
We discussed about trying out pull request templates in our repos.

## Description
This PR adds the pull request file.

- [N/A] Change the task url above to the actual Monday task
- [N/A] Add/update tests if needed
- [x] Add reviewers to this PR

### CODE REVIEW

**Comment by bryanjnelson** [comment]
In regards to the "Reason for this PR" section...do we _only_ use this if we don't have a Monday task?

**Comment by andrewmurraydavid** [comment]
> In regards to the "Reason for this PR" section...do we _only_ use this if we don't have a Monday task?

Not necessarily. I can see this being used in other use cases as well. Maybe if the task and/or story does not express any details as to what needs to be worked.

**Comment by bryanjnelson** [comment]
So "Reason for this PR" / Monday Task is more of the **why**...and the "Description" would be more of the **what**?

**Comment by andrewmurraydavid** [comment]
> So "Reason for this PR" / Monday Task is more of the **why**...and the "Description" would be more of the **what**?

Correct. At least that's what I was envisioning. Happy to adapt it to something that would make more sense.

**Review by bryanjnelson — APPROVED** [review]
I'd say this is a fine start for us.  We can always add/remove items later as desired.

Thanks @andrewmurraydavid!

**Review by willdch — APPROVED** [review]
This looks great to me!
- [x] 🤙🏼

**Review by CarsonF — APPROVED** [review]
All I see is boilerplate I need to delete or avoid while reading the description text.
But if this solves some problem for people, it's fine with me.

**Pull request merged**
